name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: sqlite3 deadman.sqlite "VACUUM;"; cargo sqlx migrate run --source=./migrations; cargo build --verbose
      env:
        DATABASE_URL: sqlite://deadman.sqlite

    - name: Run tests
      run: cargo test --verbose
      env:
        DATABASE_URL: sqlite://deadman.sqlite

