name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install cargo-hack from crates.io
      uses: baptiste0928/cargo-install@v3
      with:
      crate: sqlx-cli
      version: "^0.7"  # You can specify any semver range
    - uses: actions/checkout@v3
    - name: Build
      run: sqlite3 deadman.sqlite "VACUUM;"; cargo sqlx migrate run --source=./migrations; cargo build --verbose
      env:
        DATABASE_URL: sqlite://deadman.sqlite

    - name: Run tests
      run: cargo test --verbose
      env:
        DATABASE_URL: sqlite://deadman.sqlite

